version: '3.8'
services:
  seal:
    build: .
    volumes:
      - .:/app
    shm_size: '8gb'
    ports:
      - "9999:9999"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    command: uvicorn main:app --host 0.0.0.0 --port 9999 --reload
